#! /bin/bash

> /var/lib/nethserver/db/networks

/etc/e-smith/events/actions/nethserver-base-initialize-db
/sbin/e-smith/signal-event interface-update

/sbin/e-smith/signal-event hostname-modify

# HACK: just trick DO check script
# The file will be overwritten by the template expanded by Cockpit systemd uinit
cat << EOF > /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
EOF
